application = "业务接口自测平台"

# 雪花算法配置
[snowflake]
 machineID = 1000
 startTime = "2019-01-01"

# 数据库配置
[db]
 driver = "mysql"
 url = "platform_behavior?charset=utf8"
 host = "192.168.30.62:3306"
 username = "dev62"
 password = "dev62.123456"
 tablePrefix = "hinny_"
 maxConn = 10

# web服务配置
[server]
 host = "127.0.0.1"
 port = 18080